### ISSUE TITLE
((EliteAPI.HeatWarning)) seems identical to ((EliteAPI.Status.Overheating))

### ISSUE THREAD

**Issue by Landorin-GH** [Somfic/EliteVA#11]
Hi,

either event fires for me once heat reaches 100% so apparently they do the same job. I would have expected that HeatWarning fires at 80% (where the ingame COVAS says 'warning' as well).

According to the journal.txt it did not fire when I raised temperature above 80% but kept it below 100%:
 ###  HeatWarning  ### 
{TXT:EliteAPI.HeatWarning.event}: HeatWarning
{DATE:EliteAPI.HeatWarning.timestamp}: 08.09.2023 17:57:36

**Comment by Somfic** [comment]
Hi, EliteVA is only responsible for relaying the events the game outputs. It seems Frontier designed the `HeatWarning` event to be identical to when `Status.Overheating` is set to true. The game does not output the ship's heat as a decimal value, so it'd be hard to figure out when the ship reaches 80% heat.
