### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by Wither-Strike** [Somfic/EliteVA#14]
If time allows, I think it would be cool to add a wiki that goes over the variables and how they work, just something like "xBool is set to true when y and is set to false when z"

**Comment by Somfic** [comment]
Hi there,

Thanks for your suggestion. EliteVA can output tens of thousands of variables in a session, making it challenging to cover each one comprehensively. One of the key features of EliteVA is that the plugin is prone to future Elite Dangerous versions, meaning that in the case of events being added or changed in the future the plugin still functions as expended and picks up on these changes without hiccup. This dynamic way of detecting and generating VoiceAttack variables makes it harder to write documentation on specific variables or events.

However, there are some excellent resources available to help players understand these variables better:

- **Elite Dangerous Official Journal Manual**
The Elite Dangerous developers have put together a comprehensive manual that covers most of the game's events, when they are triggered, and what their contents are. You can find this manual at https://hosting.zaonce.net/community/journal/v37/Journal_Manual_v37.pdf.

- **Live Tools**
You can also check out EliteVA's 'live tools' feature, which provides information about variables set by the plugin. You can find it on my documentation website here https://docs.somfic.dev/projects/eliteva/live. The `Variables` section provides a list of variables which are currently set. The `Records` section you can find a list of variables that *could* potentially be set. *Note that the EliteVA plugin needs to be running locally for these tools to function.*

- **Firey Toad's tutorials**
Twitch streamer [Firey Toad](https://www.twitch.tv/fireytoad) has made a set of tutorial videos which can be found here https://www.youtube.com/watch?v=wkdpLXa1eqo&list=PLALj9exX2tHXdjsd6hx5fahOAqxGaArsD. These videos can help people get started with the plugin and give them inspiration for macros they could create with the plugin. 

In many cases, variable names are self-explanatory, which can make it easier to understand their purpose. 

However, if you have specific questions or need clarification on certain variables or groups of variables, I can offer to elaborate on them and add the explanations to the documentation website, let me know! I'm happy to answer questions :)

**Comment by Wither-Strike** [comment]
First off this was a very detailed response to such a short suggestion, thank you. I don't currently have questions on a particular variable, so I think I will close this now, I was mostly looking for somewhere that had all of them in case there were any that I didn't see yet. Thank you for the links btw, I will be checking them out
