### ISSUE TITLE
EliteVA unable to perform inputs

### ISSUE THREAD

**Issue by rhycus73** [Somfic/EliteVA#37]
**I am no longer able to get EliteVA to perform inputs for me. I've been having a whole bunch of issues leaning how VoiceAttack and this plugin works. After I took a break it wasn't performing inputs. I tried everything from running the updater, trying other plugins to map my keys, uninstalling and reinstalling EliteVA, and even restarting my whole computer. I have all my keybinds wset to cusom for all four categories with the custom 'Custom.4.1.binds' file in the Bindings folder. What am I doing wrong?

![VoiceAttack_KOe1fkGN9L](https://github.com/user-attachments/assets/747a450d-1b3d-4c51-ad50-faf71adc28fa)
![explorer_mew5mRAMum](https://github.com/user-attachments/assets/9640c75b-bd77-44bf-ae83-7ac2d8a3f590)

**Comment by UseLessUK** [comment]
Firstly you'd need to check to make sure there are keys assigned to the various functions in Elite Dangerous, if a function has no key, joystick or controller button set then the plugin when it reads the binds file will not be able to create a variable for VoiceAttack to use ... so no key gets pressed.

You should make sure at least one of the two columns available in the game to bind keys/joysticks/controllers to game functions has an actual keyboard key set, see image for example (I use a 360 controller (left column) + Keyboard (right column) (VA presses the keyboard keys))

![20230326141254_1](https://github.com/user-attachments/assets/77e8c636-c258-4cec-9618-4c3bd856b984)

**Comment by rhycus73** [comment]
I play keyboard, I have made sure to do all the basics. I actually downloaded bindED to solve the problem with it not pressing my keys but now it will not recognize API Events. It can recognize Status but not Events. I feel like I have a deep problem with the API

**Comment by rhycus73** [comment]
I should also add that I can't get live updates from the live documentation website either

**Comment by delebash** [comment]
I ran into a similar problem as a new player. In training mode, after setting up @UseLessUK VA profile no VA commands worked all with error key not found make sure it is set in the game. To fix, I had to open a session like solo session first before going into training mode and then all voice commands worked and were finding the keys.  Thank you both for the plugin and profile.  Cheers!
