### ISSUE TITLE
eliteapi.ui_select is missing

### ISSUE THREAD

**Issue by geekmoto13** [Somfic/EliteVA#39]
Trying to follow the video on the doc page for the request docking example https://docs.somfic.dev/projects/eliteva/fireytoad and the variable is missing from the bindings.txt file so I dont know if VA is even firing it off in elite dangerous.

**Comment by Somfic** [comment]
Hi @geekmoto13, this variable is only set if it's also set in-game. Is the in-game keybindining set to a keyboard-only combination, either in the primary or secondary slot? Does the plugin give you any warnings in the VoiceAttack console?

**Comment by geekmoto13** [comment]
As far as I know it’s not set to a specific binding but I haven’t checked not seen any warnings but haven’t been looking.  As for the bindings which one am I looking for?

**Comment by geekmoto13** [comment]
in game the UI_Select is set to A on my gamepad but va is giving me the error 

6:45:34.706 Key press by variable [EliteAPI.UI_Select] not set. No keys pressed.

**Comment by UseLessUK** [comment]
You need to also have a keyboard key setup for it ... use 1 column for the controller and the other for the keyboard and VA will press the keyboard key setup when the command is issued

How I have mine setup, I use a 360 controller (started playing on the Xbox and moving to the PC a controller was easier as I switched between the two platforms)
![20230326140910_1](https://github.com/user-attachments/assets/0699503a-44e9-4d34-993f-1adf16c14c8b)

**Comment by geekmoto13** [comment]
ah ok, one other question, how do you get Voice Attack to handle requests for docking if you do that, seems like the tutorial doesnt quite work right  from what i can tell it does open the "nav" panel but then it seems to get hung up there.

**Comment by UseLessUK** [comment]
Two things ...

1. You need to make sure you have keyboard keys setup for ALL the functions in game you want VA to be able to perform. VA does not press controller buttons.

2. Depends when the tutorial was done as they added another tab in an update so with the Nav panel as the active tab and getting VA to move to the contacts panel and then request docking moving back to the nav panel requires 2 moves now and not the one it used to.

When I did mine I created helper functions and pass a number to it which is then used to move a cursor/active tab the specified number of times up/down/left/right or next tab/previous tab etc

**Comment by UseLessUK** [comment]
Did you get this issue resolved?

**Comment by geekmoto13** [comment]
Yeah I did
