### ISSUE TITLE
Check if EliteVA is available?

### ISSUE THREAD

**Issue by UseLessUK** [Somfic/EliteVA#8]
Greetings,

Is there a variable I can test in VA to see if EliteVA is up and running?

Something like `EliteVA.Version` which if not set then either EliteVA isn't installed or it's still starting up.

**Comment by Somfic** [comment]
Hi @UseLessUK,

Great suggestion. Will be implemented in the next version of EliteVA.

**Comment by Somfic** [comment]
This feature is now implemented in [v0.4.0](https://github.com/Somfic/EliteVA/releases/tag/0.4.0). On startup the plugin sets `{TXT:EliteAPI.Version}` to the plugin's version.
